board/urls.py
from django.urls import path
from . import views
from board.views import base_views, question_views, answer_views, vote_views, comment_views

app_name = 'board'                                              # 네임 스페이스(소속)

urlpatterns = [
    # 인덱스 페이지
    path('', base_views.index, name='index'),                        # 127.0.0.1:8000/board/
    # 질문 목록
    path('boardlist/', base_views.boardlist, name='boardlist'),      # 127.0.0.1:8000/board/boardlist
    # 상세 페이지
    path('<int:question_id>/', base_views.detail, name='detail'),    # 127.0.0.1:8000/board/1/
    # 질문 등록 - # 127.0.0.1:8000/board/question/create/
    path('question/create/', question_views.question_create, name='question_create'),
    # 답변 등록 - # 127.0.0.1:8000/board/answer/create/1/
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    # 질문 수정
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    # 답변 수정
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    # 질문 삭제
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    # 답변 삭제
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    # 질문 추천
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    # 질문 댓글 등록
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question,
         name='comment_create_question'),
    # 질문 댓글 삭제
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question,
         name='comment_delete_question'),
    # 질문 댓글 수정
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question,
         name='comment_modify_question'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common import views

app_name = 'common'

urlpatterns = [
    # LoginView 클래스 - 제네릭 뷰
    # path('login/', auth_views.LoginView.as_view(template_name='common/login.html'),
    #      name='login'),
    path('login/', views.login_view, name='login_view'),            # 함수형 view
    # 로그아웃
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('logout/', views.logout_view, name='logout_view'),         # 함수형 view
    # 회원 가입
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views, question_views, answer_views, vote_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('board/', views.index),              # 127.0.0.1:8000/board/
    path('', base_views.index),                      # 127.0.0.1:8000/com
    path('board/', include('board.urls')),      # 127.0.0.1:8000/board/
    path('common/', include('common.urls')),    # 127.0.0.1:8000/common/
    path('poll/', include('poll.urls')),        # 127.0.0.1:8000/poll/
]

poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/vote/', views.vote, name='vote'),
]

board/views/base_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from board.models import Question, Answer
from board.forms import QuestionForm, AnswerForm

def index(request):
    # 인덱스 페이지
    question_list = Question.objects.order_by('-pk')[:3]
    context = {'question_list':question_list}
    return render(request, 'board/index.html', context)

def boardlist(request):
    # 질문 목록 페이지
    # question_list = Question.objects.all()                    # db에서 전체 검색
    question_list = Question.objects.order_by('-create_date')   # 내림차순(-) / -pk도 가능
    page = request.GET.get('page', '1')              # 페이지
    kw = request.GET.get('kw', '')

    # 검색 처리
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |                   # 제목 검색( 밑줄(_) 두개 )
            Q(content__icontains=kw) |                   # 내용 검색
            Q(author__username__icontains=kw) |          # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw) |  # 답변 글쓴이 검색
            Q(answer__content__icontains=kw) |           # 답변 내용 검색
            Q(comment__content__icontains=kw)            # 댓글 내용 검색
        ).distinct()


    # 페이징 처리
    paginator = Paginator(question_list, 10)         # 페이지당 10개 자료
    page_obj = paginator.get_page(page)
    context = {'question_list':page_obj, 'page':page, 'kw':kw}

    # return HttpResponse("<h2>Hello~ Django!!</h2>")
    return render(request, 'board/question_list.html', context)

def detail(request, question_id):
    # 상세 페이지
    question = get_object_or_404(Question, pk=question_id)      # url 경로 오류 처리(오류 대신 Page not found (404) 출력)
    # question = Question.objects.get(id=question_id)
    context = {'question':question}
    return render(request, 'board/detail.html', context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'board/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'board/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
</head>
<body>
    {% include 'navbar.html' %}
    <!-- 기본 표준 파일 안에 삽입될 내용 start -->
    {% block content %}
    <!-- 내용 -->
    {% endblock %}

    {% include 'footer.html' %}
<script src="{% static 'board/js/jquery-3.6.0.js' %}"></script>
<!--<script src="{% static 'board/js/bootstrap.js' %}"></script>        &lt;!&ndash; 순서 : jquery - bootstrap &ndash;&gt;-->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
{% block script %}
<!-- 자바 스크립트 소스 -->
{% endblock %}
</body>
</html>

templates/footer.html
<footer class="bg-dark p-3">
    <div class="container">
        <ul class="menu">
            <li><a href="#">회사소개</a></li>
            <li><a href="#">개인정보처리방침</a></li>
            <li><a href="#">이용약관</a></li>
            <li><a href="#">사이트맵</a></li>
        </ul>
        <address>
            <p>대표이사 : 파이썬 | 대표전화 : 032-262-0600</p>
            <p>주소 : 인천광역시 부평구 경원대로 1366, 상록스테이션타워 5층</p>
            <p>사업자등록번호 : 00-000-0000</p>
        </address>
    </div>
</footer>

templates/form_errors.html
<!-- 유효성 검사 -->
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ field.label }}</strong>
            {{ error }}
        </div>
        {% endfor %}
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'board:index' %}">PyWeb</a>
        <!-- 햄버거 메뉴 -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- pyweb 메뉴 -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link active" aria-current="page" href="{% url 'common:logout_view' %}">({{ user.username }}님)로그아웃</a>
                    {% else %}
                    <a class="nav-link active" aria-current="page" href="{% url 'common:login_view' %}">로그인</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'board:boardlist' %}">질문/답변</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'poll:index' %}">설문 조사</a>
                </li>
            </ul>
        </div>
    </div>
</nav>