board/urls.py
from django.urls import path
from . import views
from board.views import base_views, question_views, answer_views, vote_views, comment_views

app_name = 'board'                                              # 네임 스페이스(소속)

urlpatterns = [
    # 인덱스 페이지
    path('', base_views.index, name='index'),                        # 127.0.0.1:8000/board/
    # 질문 목록
    path('boardlist/', base_views.boardlist, name='boardlist'),      # 127.0.0.1:8000/board/boardlist
    # 상세 페이지
    path('<int:question_id>/', base_views.detail, name='detail'),    # 127.0.0.1:8000/board/1/
    # 질문 등록 - # 127.0.0.1:8000/board/question/create/
    path('question/create/', question_views.question_create, name='question_create'),
    # 답변 등록 - # 127.0.0.1:8000/board/answer/create/1/
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    # 질문 수정
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    # 답변 수정
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    # 질문 삭제
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    # 답변 삭제
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    # 질문 추천
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    # 질문 댓글 등록
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question,
         name='comment_create_question'),
    # 질문 댓글 삭제
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question,
         name='comment_delete_question'),
    # 질문 댓글 수정
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question,
         name='comment_modify_question'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from board.views import base_views, question_views, answer_views, vote_views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('board/', views.index),              # 127.0.0.1:8000/board/
    path('', base_views.index),                      # 127.0.0.1:8000/com
    path('board/', include('board.urls')),      # 127.0.0.1:8000/board/
    path('common/', include('common.urls')),    # 127.0.0.1:8000/common/
    path('poll/', include('poll.urls')),        # 127.0.0.1:8000/poll/
]

poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/vote/', views.vote, name='vote'),
]

board/models.py
from django.contrib.auth.models import User
from django.db import models


# 질문 모델
class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()                                                            # 반드시 있어야 함(NOT NULL)
    modify_date = models.DateTimeField(null=True, blank=True)                                       # null 허용, blank - 폼 데이터 null
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')      # user의 username과 외래키 설정
    voter = models.ManyToManyField(User, related_name='voter_question')                             # 추천수 - 다대다 관계

    def __str__(self):
        return self.subject

# 답변 모델
class Answer(models.Model):
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)          # user의 username과 외래키 설정

    def __str__(self):
        return self.content

# 댓글 모델
class Comment(models.Model):
    content = models.TextField()                                        # 댓글 내용
    create_date = models.DateTimeField()                                # 댓글 작성일
    modify_date = models.DateTimeField(null=True, blank=True)           # 댓글 수정일
    author = models.ForeignKey(User, on_delete=models.CASCADE)          # 외래키 - 댓글 글쓴이
    question = models.ForeignKey(Question, null=True, blank=True,
                                 on_delete=models.CASCADE)              # 댓글이 달린 질문, 없어도 되므로 null, blank 추가
    answer = models.ForeignKey(Answer, null=True, blank=True,
                               on_delete=models.CASCADE)                # 댓글이 달린 답변

    def __str__(self):
        return self.content

board/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from board.models import Question, Answer
from board.forms import QuestionForm, AnswerForm

def index(request):
    # 인덱스 페이지
    question_list = Question.objects.order_by('-pk')[:3]
    context = {'question_list':question_list}
    return render(request, 'board/index.html', context)

def boardlist(request):
    # 질문 목록 페이지
    # question_list = Question.objects.all()                    # db에서 전체 검색
    question_list = Question.objects.order_by('-create_date')   # 내림차순(-) / -pk도 가능

    # 페이징 처리
    page = request.GET.get('page', '1')              # 페이지
    paginator = Paginator(question_list, 10)         # 페이지당 10개 자료
    page_obj = paginator.get_page(page)
    context = {'question_list':page_obj}

    # return HttpResponse("<h2>Hello~ Django!!</h2>")
    return render(request, 'board/question_list.html', context)

def detail(request, question_id):
    # 상세 페이지
    question = get_object_or_404(Question, pk=question_id)      # url 경로 오류 처리(오류 대신 Page not found (404) 출력)
    # question = Question.objects.get(id=question_id)
    context = {'question':question}
    return render(request, 'board/detail.html', context)

@login_required(login_url='common:login_view')
def question_create(request):
    # 질문 등록
    if request.method == "POST":
        form = QuestionForm(request.POST)       # 내용이 작성된 폼
        if form.is_valid():
            question = form.save(commit=False)      # 가저장
            question.create_date = timezone.now()   # 작성일
            question.author = request.user          # 인증된 사용자(글쓴이)
            question.save()                         # 실제 저장
            return redirect('board:boardlist')          # 질문 목록 페이지 강제 이동
    else:   # request.method == "GET"
        form = QuestionForm         # 질문 등록 폼 객체 변수 생성 (비어있는 폼)
    context = {'form':form}
    return render(request, 'board/question_form.html', context)   # 공통

@login_required(login_url='common:login_view')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)      # url 경로 오류 처리
    # question = Question.objects.get(id=question_id) # 해당 질문 1개 가져옴
    if request.method == "POST":
        form = AnswerForm(request.POST)             # 데이터가 채워진 폼
        if form.is_valid():                         # 유효성 검사
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.author = request.user            # 인증된 사용자(글쓴이)
            answer.save()
            return redirect('board:detail', question_id=question_id)
    else:
        form = AnswerForm()                         # 비어있는 폼
    context = {'form':form, 'question':question}
    return render(request, 'board/detail.html', context)

@login_required(login_url='common:login_view')
def question_modify(request, question_id):
    # 질문 수정
    question = get_object_or_404(Question, pk=question_id)
    # question = Question.objects.get(id=question_id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)         # 새로 작성한 폼
        if form.is_valid():
            question = form.save(commit=False)                       # 가저장
            question.modify_date = timezone.now()                    # 수정일
            question.author = request.user                           # 글쓴이
            question.save()                                          # db에 저장
            return redirect('board:detail', question_id=question_id)
    else:
        form = QuestionForm(instance=question)                       # 이미 작성된 폼
    context = {'form':form}
    return render(request, 'board/question_form.html', context)

@login_required(login_url='common:login_view')
def answer_modify(request, answer_id):
    # 답변 수정
    answer = get_object_or_404(Answer, pk=answer_id)
    # answer = Answer.objects.get(id=answer_id)
    form = AnswerForm(request.POST, instance=answer)  # 수정할 답변 폼
    if request.method == "POST":
        answer = form.save(commit=False)
        answer.modify_date = timezone.now()
        answer.author = request.user
        answer.save()                                               # db에 저장
        return redirect('board:detail', question_id = answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'form':form}
    return render(request, 'board/answer_form.html', context)

@login_required(login_url='common:login_view')
def question_delete(request, question_id):
    # 질문 삭제
    question = get_object_or_404(Question, pk=question_id)
    # question = Question.objects.get(id=question_id)
    question.delete()                                               # 해당 질문 삭제
    return redirect('board:boardlist')                                  # 질문 목록

@login_required(login_url='common:login_view')
def answer_delete(request, answer_id):
    # 답변 삭제
    answer = get_object_or_404(Answer, pk=answer_id)
    # answer = Answer.objects.get(id=answer_id)
    answer.delete()
    return redirect('board:detail', question_id=answer.question.id)  # 상세 페이지

@login_required(login_url='common:login_view')
def vote_question(request, question_id):
    # 질문 추천
    question = get_object_or_404(Question, pk=question_id)
    # question = Question.objects.get(id=question_id)
    if request.user == question.author:
        messages.error(request, "본인이 작성한 글은 추천할 수 없습니다.")
    else:
        question.voter.add(request.user)                    # 추천 1 증가
    return redirect('board:detail', question_id=question_id)

board/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from board.models import Question, Answer
from board.forms import QuestionForm, AnswerForm

@login_required(login_url='common:login_view')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)      # url 경로 오류 처리
    # question = Question.objects.get(id=question_id) # 해당 질문 1개 가져옴
    if request.method == "POST":
        form = AnswerForm(request.POST)             # 데이터가 채워진 폼
        if form.is_valid():                         # 유효성 검사
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.author = request.user            # 인증된 사용자(글쓴이)
            answer.save()
            return redirect('board:detail', question_id=question_id)
    else:
        form = AnswerForm()                         # 비어있는 폼
    context = {'form':form, 'question':question}
    return render(request, 'board/detail.html', context)

@login_required(login_url='common:login_view')
def answer_modify(request, answer_id):
    # 답변 수정
    answer = get_object_or_404(Answer, pk=answer_id)
    # answer = Answer.objects.get(id=answer_id)
    form = AnswerForm(request.POST, instance=answer)  # 수정할 답변 폼
    if request.method == "POST":
        answer = form.save(commit=False)
        answer.modify_date = timezone.now()
        answer.author = request.user
        answer.save()                                               # db에 저장
        return redirect('board:detail', question_id = answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'form':form}
    return render(request, 'board/answer_form.html', context)

@login_required(login_url='common:login_view')
def answer_delete(request, answer_id):
    # 답변 삭제
    answer = get_object_or_404(Answer, pk=answer_id)
    # answer = Answer.objects.get(id=answer_id)
    answer.delete()
    return redirect('board:detail', question_id=answer.question.id)  # 상세 페이지

board/views/base_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from board.models import Question, Answer
from board.forms import QuestionForm, AnswerForm

def index(request):
    # 인덱스 페이지
    question_list = Question.objects.order_by('-pk')[:3]
    context = {'question_list':question_list}
    return render(request, 'board/index.html', context)

def boardlist(request):
    # 질문 목록 페이지
    # question_list = Question.objects.all()                    # db에서 전체 검색
    question_list = Question.objects.order_by('-create_date')   # 내림차순(-) / -pk도 가능
    page = request.GET.get('page', '1')              # 페이지
    kw = request.GET.get('kw', '')

    # 검색 처리
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |                   # 제목 검색( 밑줄(_) 두개 )
            Q(content__icontains=kw) |                   # 내용 검색
            Q(author__username__icontains=kw) |          # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw) |  # 답변 글쓴이 검색
            Q(answer__content__icontains=kw) |           # 답변 내용 검색
            Q(comment__content__icontains=kw)            # 댓글 내용 검색
        ).distinct()


    # 페이징 처리
    paginator = Paginator(question_list, 10)         # 페이지당 10개 자료
    page_obj = paginator.get_page(page)
    context = {'question_list':page_obj, 'page':page, 'kw':kw}

    # return HttpResponse("<h2>Hello~ Django!!</h2>")
    return render(request, 'board/question_list.html', context)

def detail(request, question_id):
    # 상세 페이지
    question = get_object_or_404(Question, pk=question_id)      # url 경로 오류 처리(오류 대신 Page not found (404) 출력)
    # question = Question.objects.get(id=question_id)
    context = {'question':question}
    return render(request, 'board/detail.html', context)

board/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from board.models import Question, Answer, Comment
from board.forms import QuestionForm, AnswerForm, CommentForm

@login_required(login_url='common:login_view')
def comment_create_question(request, question_id):
    # 질문 댓글 등록
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)       # 가저장
            comment.create_date = timezone.now()    # 댓글 작성일
            comment.author = request.user           # 댓글 글쓴이
            comment.question = question             # 댓글이 달린 질문
            comment.save()                          # db에 저장
            return redirect('board:detail', question_id=question.id)
    else:
        form = CommentForm()                        # 비어있는 폼
    context = {'form':form}
    return render(request, 'board/comment_form.html', context)

@login_required(login_url='common:login_view')
def comment_delete_question(request, comment_id):
    # 질문 댓글 삭제
    comment = Comment.objects.get(id=comment_id)    # 질문 댓글 1개 가져오기
    comment.delete()                                # 삭제
    return redirect('board:detail', question_id=comment.question.id)

@login_required(login_url='common:login_view')
def comment_modify_question(request, comment_id):
    # 질문 댓글 수정
    comment = Comment.objects.get(id=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)      # 새로 수정한 댓글
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.author = request.user
            comment.save()
            return redirect('board:detail', question_id=comment.question.id)

    else:
        form = CommentForm(instance=comment)            # 기존 작성된 댓글 폼
    context = {'form':form}
    return render(request, 'board/comment_form.html', context)

board/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from board.models import Question, Answer
from board.forms import QuestionForm, AnswerForm

@login_required(login_url='common:login_view')
def vote_question(request, question_id):
    # 질문 추천
    question = get_object_or_404(Question, pk=question_id)
    # question = Question.objects.get(id=question_id)
    if request.user == question.author:
        messages.error(request, "본인이 작성한 글은 추천할 수 없습니다.")
    else:
        question.voter.add(request.user)                    # 추천 1 증가
    return redirect('board:detail', question_id=question_id)

templates/board/detail.html
{% extends 'base.html' %}
{% block title %}
  Question - {{ question.subject }}
{% endblock %}

{% block content %}
    <div class="container my-3">
        <!-- 추천 오류 표시 -->
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger my-3">
                <ul>
                    <li>{{ message.message }}</li>
                </ul>
                </div>
            {% endfor %}
        {% endif %}
       <h2 class="border-bottom py-2">{{ question.subject }}</h2>
        <!-- 질문 추천영역과 질문 영역으로 구분 -->
        <div class="row">
            <!-- 질문 추천 영역 -->
            <div class="col-1">
                <div class="bg-light text-center border p-3 font-weight-bolder">
                    <!--{{ 0 }}--> {{ question.voter.count }}
                </div>
                <a href="#" data-uri="{% url 'board:vote_question' question.id %}"
                   class="recommend btn btn-secondary btn-block my-1">추천</a>
            </div>
            <!-- 질문 영역 -->
            <div class="col-11">
                <div class="card my-3">
                    <div class="card-body">
                        <div class="card-text" style="white-space:pre-line">
                            {{ question.content }}
                        </div>
                        <div class="d-flex justify-content-end">
                            {% if question.modify_date %}  <!-- 수정일이 있다면 -->
                            <div class="badge badge-light text-dark p-2 mx-3 text-left">
                                <div class="mb-2">modified at</div>
                                <div>{{ question.modify_date }}</div>
                            </div>
                            {% endif %}
                            <div class="badge badge-light text-dark p-2 text-left">
                                <div class="mb-2">{{ question.author }}</div>
                                <div>{{ question.create_date }}</div>
                            </div>
                        </div>
                        <!-- 질문 수정, 삭제 버튼 -->
                        {% if request.user == question.author %}
                        <div>
                            <a href="{% url 'board:question_modify' question.id %}"
                               class="btn btn-outline-secondary">수정</a>
                            <a href="#" data-uri="{% url 'board:question_delete' question.id %}"
                               class="delete btn btn-outline-secondary">삭제</a>
                            <!--
                            <a href="{% url 'board:question_delete' question.id %}"
                               onclick="return confirm('정말로 삭제하시겠습니까?')"
                               class="btn btn-outline-secondary">삭제</a>-->
                        </div>
                        {% endif %}
                        <div class="mt-3">
                            {% for comment in question.comment_set.all %}
                            <div class="comment text-muted py-2 small">
                                <span style="white-space: pre-line;">{{ comment.content }}</span><br>
                                <span>
                                    -{{ comment.author }}, {{ comment.create_date }}
                                    {% if comment.modify_date %}
                                    (수정일 : {{ comment.modify_date }})
                                    {% endif %}
                                </span>
                                {% if request.user == comment.author %}
                                <a href="{% url 'board:comment_modify_question' comment.id %}">수정</a>
                                <a href="#" class="delete"
                                   data-uri="{% url 'board:comment_delete_question' comment.id %}">삭제</a>
<!--                                <a href="{% url 'board:comment_delete_question' comment.id %}"-->
<!--                                   onclick="return confirm('정말로 삭제하시겠습니까?')">삭제</a>-->
                                {% endif %}
                            </div>
                            {% endfor %}
                        </div>
                        <div>
                            <a href="{% url 'board:comment_create_question' question.id %}"
                            class="text-decoration-none small">댓글 추가..</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- 답변 영역 -->
        <h5 class="border-bottom my-3 py-2">
            {{ question.answer_set.count }}개의 답변이 있습니다.
        </h5>
        {% for answer in question.answer_set.all %}
        <div class="card my-3">
            <div class="card-body">
                <div class="card-text" style="white-space:pre-line">{{ answer.content }}</div>
                <div class="d-flex justify-content-end">
                    {% if answer.modify_date %}  <!-- 답변 수정일이 있다면 -->
                    <div class="badge badge-light badge text-dark p-2 mx-3 text-left">
                        <div class="mb-2">modified at</div>
                        <div>{{ answer.modify_date }}</div>
                    </div>
                    {% endif %}
                    <div class="badge badge-light badge text-dark p-2 text-left">
                        <div class="mb-2">{{ answer.author }}</div>
                        <div>{{ answer.create_date }}</div>
                    </div>
                </div>
                <!-- 답변 수정, 삭제 버튼 -->
                {% if request.user == answer.author %}
                <div>
                    <a href="{% url 'board:answer_modify' answer.id %}"
                       class="btn btn-outline-secondary">수정</a>
                    <a href="#" data-uri="{% url 'board:answer_delete' answer.id %}"
                       class="delete btn btn-outline-secondary">삭제</a>
                    <!--
                    <a href="{% url 'board:answer_delete' answer.id %}"
                       onclick="return confirm('정말로 삭제하시겠습니까?')"
                       class="btn btn-outline-secondary">삭제</a>-->
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        <!-- 답변 등록 -->
        <form action="{% url 'board:answer_create' question.id %}" method="post">
            {% csrf_token %}
            {% include 'form_errors.html' %}
            <div class="form-group">
                <textarea name="content" rows="7" cols="60" class="form-control"
                        {% if not user.is_authenticated %} disabled {% endif %}></textarea>
            </div>
            <input type="submit" value="답변 등록" class="btn btn-primary">
        </form>
    <div class="detail"></div>
    </div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function(){
        //삭제 처리
        $('.delete').click(function(){
            if(confirm('정말로 삭제하시겠습니까?')){
                location.href = $(this).data('uri');
            }
        });

        //추천 처리
        $('.recommend').click(function(){
            if(confirm('정말로 추천하시겠습니까?')){
                location.href = $(this).data('uri'); //uri 경로로 이동
            }
        });
    });
</script>
{% endblock %}
<!--
      <h2>{{ question.subject }}</h2>
      <p>{{ question.content }}</p>
      <h4>{{ question.answer_set.count }}개의 답변이 있습니다.</h4>
      <div>
          <ul>
              {% for answer in question.answer_set.all %}
              <li>{{ answer.content }}</li>
              {% endfor %}
          </ul>
      </div>
      <form action="{% url 'board:answer_create' question.id %}" method="post">
          {% csrf_token %}
          <div>
              <textarea name="content" rows="7" cols="60"></textarea>
          </div>
          <input type="submit" value="답변 등록">
      </form>
      -->

templates/board/question_list.html
{% extends 'base.html' %}
{% load board_filter %}         <!-- 필터 로딩 -->
{% block title %}
질문 / 답변 목록
{% endblock %}
{% block content %}

    <div class="container my-3">
        <!-- 검색 입력 상자 -->
        <div class="row justify-content-end mb-2">
            <div class="col-4 input-group">
                <input type="text" class="kw" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button type="button" id="btn_search"
                            class="btn btn-outline-secondary">검색</button>
                </div>
            </div>
        </div>
        <!-- 게시판 목록 테이블 -->
        <table class="table">
            <thead class="thead-dark">
                <tr class="text-center">
                    <th>번호</th><th>추천</th><th>제목</th><th>글쓴이</th><th>작성일</th>
                </tr>
            </thead>
            <tbody>
                {% if question_list %}
                    {% for question in question_list %}
                <tr class="text-center">
                    <!-- 번호 = 전체 게시물 수 - 시작 인덱스 - 현재 인덱스(0~9) + 1 -->
                    <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
<!--                    <td>{{ forloop.counter|add:3 }}</td>-->
                    <td>
                        {% if question.voter.count > 0 %}
                        <span class="badge badge-warning text-dark px-2 py-1">{{ question.voter.count }}</span>
                        {% endif %}
                    </td>
                    <td class="text-left px-3">
                        <a href="{% url 'board:detail' question.id %}"
                           class="text-decoration-none text-dark">{{ question.subject }}</a>
                        {% if question.answer_set.count > 0 %}
                        <span class="text-danger small">[{{ question.answer_set.count }}]</span>
                        {% endif %}
                    </td>
                    <td>
                        {{ question.author }}
                    </td>
                    <td>
                        {{ question.create_date }}
                    </td>
                </tr>
                    {% endfor %}
                {% else %}
                <p>질문이 없습니다.</p>
                {% endif %}
            </tbody>
        </table>
        <!-- 페이지 처리 영역 -->
        <!-- 페이지 리스트(목록) -->
        <ul class="pagination justify-content-center">
        <!-- 이전 페이지 -->
            {% if question_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">이전</a>
            </li>
            {% endif %}
        {% for page_number in question_list.paginator.page_range %}
            {% if page_number == question_list.number %}            <!-- 클릭한 페이지가 현재 페이지이면 -->
            <li class="page-item active">                           <!-- 버튼 활성화 -->
<!--                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>-->
                <a class="page-link" href="#" data-page="{{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
<!--                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>-->
                <a class="page-link" href="#" data-page="{{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endfor %}
            <!-- 다음 페이지 -->
            {% if question_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <a href="{% url 'board:question_create' %}" class="btn btn-primary">질문 등록</a>
        <div class="question_list"></div>
        <!-- 검색 폼 만들기 -->
        <form method="get" id="searchForm">             <!-- get 방식 -->
            <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
            <input type="hidden" id="page" name="page" value="{{ page }}">
        </form>
    </div>
{% endblock %}
{% block script %}
<script>
    $(function(){                                   // (document).ready 생략
        // 페이지 처리
        $('.page-link').click(function(){           // 페이지 번호를 클릭하면
            $('#page').val($(this).data('page'))    // 페이지 번호를 id가 page인 필드에 설정 후
            $('#searchForm').submit();              // 숨겨서 폼을 전송함
        });

        // 검색 처리
        $('#btn_search').click(function(){          // '검색'을 클릭하면
            $('#kw').val($('.kw').val());            // 입력된 키워드를 id가 kw인 필드에 설정
            $('#page').val(1);                      // 1페이지부터 검색
            $('#searchForm').submit();              // 숨겨서 폼을 전송함
        });
    });
</script>
{% endblock %}

        <!-- 부트 스트랩 적용 전
        <h1>질문 목록입니다.</h1>
        {% if question_list %}
        <ul>
            {% for question in question_list %}
            <li>
                <a href="{% url 'board:detail' question.id %}">{{ question.subject }}</a>        #네임 스페이스 사용
                # <a href="board/{{ question.id }}/">{{ question.subject }}</a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <p>질문이 없습니다.</p>
        {% endif %}
        <a href="{% url 'board:question_create' %}">질문 등록</a>
        -->


        <!-- 페이지 처리 영역 -->
<!-- <p class="text-center">1 2 3</p>-->
<!--
<ul class="text-center">
    {% for question in question_list %}
    {% if forloop.counter < 5 %}
    <li style="list-style:none; display: inline;">
        <a href="#">{{ forloop.counter }}&nbsp;</a>
    </li>
    {% endif %}
    {% endfor %}
</ul>
-->